/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -p org_kde_solid_networking /home/andreas/Programing/C++/network-manager-ipop/kde/solidcontrolfuture/libs/solid/control/org.kde.Solid.Networking.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "org_kde_solid_networking.h"

/*
 * Implementation of interface class OrgKdeSolidNetworkingInterface
 */

OrgKdeSolidNetworkingInterface::OrgKdeSolidNetworkingInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeSolidNetworkingInterface::~OrgKdeSolidNetworkingInterface()
{
}


#include "org_kde_solid_networking.moc"
