/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -c GsmInterfaceConnectionInterface -p gsminterfaceconnectioninterface /home/andreas/Programing/C++/network-manager-ipop/kde/libs/service/interfaces/org.kde.networkmanagement.gsminterfaceconnection.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "gsminterfaceconnectioninterface.h"

/*
 * Implementation of interface class GsmInterfaceConnectionInterface
 */

GsmInterfaceConnectionInterface::GsmInterfaceConnectionInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

GsmInterfaceConnectionInterface::~GsmInterfaceConnectionInterface()
{
}


#include "gsminterfaceconnectioninterface.moc"
